version: '2'

services:
  
  nginx:
    build: ./containers/nginx/
    links:
     - php
    ports:
     - "60080:80"
    volumes_from:
     - php

  nginx-dev:
    build: ./containers/nginx-dev/
    links:
     - php-dev
    ports:
     - "50080:80"
    volumes_from:
     - php-dev

  pg:
    build: ./containers/pg/
    ports:
     - "55432:5432"
    volumes:
     - ./runtime/pg/data:/var/lib/postgresql/data
    env_file: ./containers/pg/.env

  php:
    links:
     - pg
    build: ./containers/php/
    volumes:
     - ./app:/app/htdocs
     - ./runtime/logs:/app/log
     - ./mount:/app/mount

  php-dev:
    links:
     - pg
    # - php-deamons
    build: ./containers/php-dev/
    volumes:
     - ./app:/app/htdocs
     - ./runtime/logs:/app/log
     - ./mount:/app/mount

  # dependency containers

  node:
    build: ./containers/node/
    volumes:
     - ./app:/app/htdocs
    ports:
     - "3000:3000"
     - "3001:3001"

  # util containers
  phpunit:
    build: ./containers/phpunit/
    volumes:
     - ./app:/app/htdocs
     - ./runtime/logs:/app/log
